### PR TITLE
Fix FP: Ignore duplicated struct tags on S1192

### LINKED ISSUE #337: FP on S1192 StringLiteralDuplicatedCheck: String literals should not be duplicated produces false positives with struct tags
Struct tags should be excluded from the duplication checking as they have to be string literals.

For example:
```
struct {
A int `json:",string"`
B int `json:",string"`
C int `json:",string"`
}
```
will be marked as a critical code smell: "Define a constant instead of duplicating this literal 3 times." In go these tags cannot be defined as const.

### PR DESCRIPTION
**Pull request by kumako**
Fixes #337

### CODE REVIEW

**Comment by saberduck** [comment]
thank you for your contribution, I will check later this week why the travis build failed, most likely it's misconfigured and doesn't handle external PR properly.

**Comment by monofone** [comment]
@saberduck Hey did you find time to check the problem behind the failing test ? would be nice to get rid of those false positives, thx

**Comment by oli-haley** [comment]
@saberduck did you get a chance to look into this? Be wicked to get it in.

**Comment by saberduck** [comment]
sorry, we haven't spent a lot of time on sonar-go lately, and we are quite busy with other language analyzers currently. I expect we will work on sonar-go bit later, maybe Q2.

**Comment by oli-haley** [comment]
@saberduck, no problem thanks for the quick response.

**Comment by kmcrawford** [comment]
This is causing serious headaches for us, can we get this pr merged in?  If help is needed, I would be happy to help move this along. @saberduck  the travis error is `./travis.sh: line 30: SONAR_HOST_URL: unbound variable`

**Comment by domoniquecarter35** [comment]
Has this made any progress? It's crucial to our CI pipeline.

**Comment by saberduck** [comment]
@domoniquecarter35  sorry, no progress on this

**Comment by Kreozot** [comment]
Can we help with this?

**Comment by saberduck** [comment]
Thanks for your contribution and I am sorry for the time it took to integrate this. I had to create a new PR #367 because of misconfiguration of our CI on travis, so I am going to close this one.

**Pull request closed without merging**
