### PR TITLE
Add golangci-lint format accepted

### PR DESCRIPTION
**Pull request by srizzling**
Resolves #355.

Adds native support for golangci-lint reports.

To use the new format, one must run the following golangci-lint command:

```
golangci-lint run --out-format tab > golangci-lint-output.txt
```

cc\ @pwmcintyre

### CODE REVIEW

**Comment by srizzling** [comment]
Tests failing don't seem to be the fault of the changes made here.

**Comment by Nerzal** [comment]
Any News on this?
Or can we help anyhow? I want this :D 

Build Fail really feels unrelated.
> ./travis.sh: line 30: SONAR_HOST_URL: unbound variable
> The command "./travis.sh" exited with 1.

**Comment by saberduck** [comment]
hey @Nerzal  @srizzling ,

thanks for your interest. Unfortunately we are bit busy now, and we will not work on this in the short-term. You can consider using this feature of SonarQube  https://docs.sonarqube.org/latest/analysis/generic-issue/  to import the issues in the meanwhile.

**Comment by Nerzal** [comment]
That's pretty sad to hear, that golang has no priority.
Can this work arround also be done in SonarCloud? 

Feels like SonarSource don't want to support golang, which is one of the fastest growing programming languages world wide. And there are people offering help and i bet it would be a lot more, if this project wouldn't be ignored that much

I cannot understand how you deny people to work on this open source project, closing Issues with suggestions how to bring more people to contribute. That's terribly frustrating.

**Comment by srizzling** [comment]
Its OK. I can understand.. I'll try writing to reversing the import of issues.

**Comment by saberduck** [comment]
Generic issue import works also on SonarCloud

**Comment by saberduck** [comment]
I am closing this PR. It is better to use the generic issue import feature instead
https://docs.sonarqube.org/latest/analysis/generic-issue/

**Pull request closed without merging**
